### ISSUE TITLE
/admin/install Not found

### ISSUE THREAD

**Issue by halojoy** [forkbb/forkbb#16]
Trying rev57.
But I get a redirect to: localhost/forkbb/public/admin/install
and so get an error from that: Not found

What is the problem?

**Comment by MioVisman** [comment]
Apache server?
The forum engine is copied to the forkbb folder of the localhost website.
So you need to rename the .dist.htaccess (to .htaccess) and index.dist.php (to index.php) files located in localhost/forkbb/, and not in localhost/forkbb/public/
And open the path localhost/forkbb/ to start the installation.
![test](https://github.com/forkbb/forkbb/assets/5917956/6c8f9034-5afc-4b5b-95f0-88ce13656b5a)

**Comment by halojoy** [comment]
Thanks I will try

**Comment by halojoy** [comment]
Now I did what you said.
Now I get a redirect to: localhost/forkbb/admin/install
And the same error: Not found

Yes, I run Apache with mod rewrite

Several other  php applications work alright.

**Comment by MioVisman** [comment]
Very strange. I see no problems on Apache 2.4.35.
Look at the contents of the Apache error log, it's Apache, not php. Maybe there is information about why mod_rewrite does not work.

**Comment by halojoy** [comment]
I run Apache 2,4,52
And I can see nothing in the error log regarding my requests.

**Comment by halojoy** [comment]
I did a fresh install of phpBB 3.3.10
They also use .htaccess with mod_rewrite.
There was no errors whatsoever. So now I have a phpbb forum.

I recently upgraded to PHP 8.2.6

**Comment by halojoy** [comment]
I managed to solve this issue.
I had 'AllowOverride None' in httpd.conf
I changed to 'AllowOverride All'
Now it works!!

**Comment by MioVisman** [comment]
Very good.
From documentation:
```
AllowOverride None (2.3.9 and later), AllowOverride All (2.3.8 and earlier)
```
I will have to make changes based on `AllowOverride None` :(

**Comment by MioVisman** [comment]
It's very strange that phpbb can run with `AllowOverride None`
With this setting, none of the .htaccess commands are executed. You can safely view all files and directories, even closed via `Deny from All`.

**Comment by MioVisman** [comment]
`AllowOverride None` disables .htaccess execution completely.

**Comment by halojoy** [comment]
Yes, completely.
phpBB  probably already has designed for  AllowOverride  None case.
