### ISSUE TITLE
Admin > User Groups - Server tired

### ISSUE THREAD

**Issue by pitamatein** [forkbb/forkbb#19]
ForkBB rev.59 Alpha

Selecting User Groups goes to Server tired :( page

**Comment by pitamatein** [comment]
Also, uploading image using imgbb sometimes takes me to a 403 page. It has worked before, but sometimes it goes to  403. Does not seem to be related to user group or permissions. Bug, or am I missing something? CSP issue maybe, I have made changes there.

**Comment by MioVisman** [comment]
Please open Administration -> Logs -> log of the current day 
And show errors

**Comment by pitamatein** [comment]
```
2023-07-09 16:54:55 error PHP OTHER_ERROR: File (en/admin_groups.po) format error in .../app/Core/Lang.php:[200]

Array
(
    [exception] => RuntimeException: File (en/admin_groups.po) format error in .../app/Core/Lang.php:200
Stack trace:
#0 .../app/Core/Lang.php(144): ForkBB\Core\Lang->arrayFromStr()
#1 .../app/Models/Pages/Admin/Groups.php(27): ForkBB\Core\Lang->load()
#2 .../app/Core/Container.php(121): ForkBB\Models\Pages\Admin\Groups->__construct()
#3 .../app/Controllers/Routing.php(807): ForkBB\Core\Container->__get()
#4 .../app/Core/Container.php(117): ForkBB\Controllers\Routing->routing()
#5 .../app/bootstrap.php(80): ForkBB\Core\Container->__get()
#6 .../index.php(14): require('/home/abolus/pu...')
#7 {main}
)
```

**Comment by MioVisman** [comment]
>CSP issue maybe,

Watch the browser console and network requests in the browser in the developer tools.
In the queries, the headlines of both the request and the server response show
If you deleted CSP, then you should see in .htaccess. There is also CSP settings there.

**Comment by pitamatein** [comment]
I think it might be related to my host and mod_security or other things they monitor.

**Comment by MioVisman** [comment]
>PHP OTHER_ERROR: File (en/admin_groups.po)

fix https://github.com/forkbb/forkbb/commit/fd625f45b518c00fbff46ead432b36d61e74a524

**Comment by MioVisman** [comment]
>mod_security 

Yes, mod_security even bugged with FLUXBB.

P.S. Google Translate is very strange to translation and reverse translation O_o

**Comment by MioVisman** [comment]
second fix https://github.com/forkbb/forkbb/commit/2c3cc72d9d8033e67bc68febdd115c52fd9b8448

**Comment by pitamatein** [comment]
I should have created separate issues. Regarding the 403 error...

`[url=https://imgbb.com/][img]https://i.ibb.co/n3CQpx2/Foghorn-Leghorn.png[/img][/url]
[url=https://ibb.co/FhGh93n][img]https://i.ibb.co/fXmXbFQ/1688868697440154.jpg[/img][/url]
`

imgbb returns either ibb.co or imgbb.com in the URL  (maybe based on if it needed a thumbnail?)

imgbb.com causes 403 error

**Comment by MioVisman** [comment]
Try to look into the server error log, not php, but the server.

I have these bbcodes inserted without problems:
![1](https://github.com/forkbb/forkbb/assets/5917956/e2d9bd57-a68d-4e31-b50f-6927d4bb70d7)

**Comment by MioVisman** [comment]
>second fix https://github.com/forkbb/forkbb/commit/2c3cc72d9d8033e67bc68febdd115c52fd9b8448

Have you used this fix or not?

**Comment by pitamatein** [comment]
Yes made all fixes.

Re logs, I  see this but don't know what it means.

```
173.236.29.82 - - [09/Jul/2023:07:12:06 -0500] "GET /.well-known/acme-challenge/XXPGQ392HJD5Z-UR48KJJCEDPGJCUAR3 HTTP/1.1" 200 64 "-" "Cpanel-HTTP-Client/1.0"
173.236.29.82 - - [09/Jul/2023:07:12:07 -0500] "GET /.well-known/acme-challenge/U_F7YZQ16GPHIC8FB4RCSUSFDHDHD9E2 HTTP/1.1" 200 64 "-" "Cpanel-HTTP-Client/1.0"
173.236.29.82 - - [09/Jul/2023:07:12:07 -0500] "GET /.well-known/acme-challenge/NA2FW9I4ZN-RVA1J00Q1KE_LGNY47WMR HTTP/1.1" 200 64 "-" "Cpanel-HTTP-Client/1.0"
173.236.29.82 - - [09/Jul/2023:10:12:06 -0500] "GET /.well-known/acme-challenge/8GFJQE_P4SV1QGAB0Y-5JG8ZYIVFA5JV HTTP/1.1" 200 64 "-" "Cpanel-HTTP-Client/1.0"
173.236.29.82 - - [09/Jul/2023:10:12:07 -0500] "GET /.well-known/acme-challenge/CL3BDQG-GC1-JMWY24JFE8ZKYHB2NKA2 HTTP/1.1" 200 64 "-" "Cpanel-HTTP-Client/1.0"
173.236.29.82 - - [09/Jul/2023:10:12:07 -0500] "GET /.well-known/acme-challenge/-OS_L5XS4V_NGOS5V6QT8SAXFJGNLOAL HTTP/1.1" 200 64 "-" "Cpanel-HTTP-Client/1.0"

```

**Comment by MioVisman** [comment]
>Re logs, I see this but don't know what it means.

Probably requests from Let's Encrypt https://letsencrypt.org/docs/challenge-types/

**Comment by pitamatein** [comment]
https://www.rfc-editor.org/rfc/rfc8615

I'll put in a support ticket with host and ask about this. Not sure if this is the issue, but I need to learn more about how this works.

**Comment by pitamatein** [comment]
The string 'imgbb.com' was triggering a ModSecurity rule, so it was server-side and not related to ForkBB

_____________

Hello Peter,

Thank you for reaching out to us today.

This action did trigger one of ModSecurity rules. It seems that this domain was listed as known thread.

**Comment by MioVisman** [comment]
ok
