### ISSUE TITLE
admin recalculate posts

### ISSUE THREAD

**Issue by pitamatein** [forkbb/forkbb#20]
It is not recalculating total topics.

**Comment by MioVisman** [comment]
Recalculation of posts was made due to the presence/absence of forums with uncountable messages. Topics are considered in any forum.

When does the situation arise that the number of topics is incorrect?

**Comment by pitamatein** [comment]
https://www.woodcentral.com/forkbb/user/2440/Mark%20Mandell

He had posted using different usernames over the years. I updated the posts and topics tables to change them all to this username and user ID.

**Comment by MioVisman** [comment]
https://github.com/forkbb/forkbb/commit/dacb8a3191384845b828ec96780803de41de3e35
https://github.com/forkbb/forkbb/commit/1e29f0a0baf62a98cc97724592adda959bfe215e

Please test.
