### ISSUE TITLE
Maintenance mode not working

### ISSUE THREAD

**Issue by pitamatein** [forkbb/forkbb#21]
Admin login shows being in Maintenance Mode, but when viewed in a private tab or another browser, the forum works normally. This is on the WoodCentral site.

**Comment by MioVisman** [comment]
/app/config/main.php
replace
`   'MAINTENANCE_OFF'  => true,`
to
`   'MAINTENANCE_OFF'  => false,`

**Comment by pitamatein** [comment]
> /app/config/main.php replace ` 'MAINTENANCE_OFF' => true,` to ` 'MAINTENANCE_OFF' => false,`

Thank you!
