### ISSUE TITLE
url Mod Rewrite

### ISSUE THREAD

**Issue by codeplay-code** [forkbb/forkbb#24]
Mod Rewrite 

exemple your forum https://forkbb.ru/topic/28/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%20%28Installation%29

to 
https://forkbb.ru/topic/28/Installation

**Comment by MioVisman** [comment]
Url depends on the topic name. Name the topic "Installation" -> get the url https://forkbb.ru/topic/28/Installation

%D0%A3 and so on are UTF-8 characters encoded in accordance with the specification other than standard Latin. I didn't come up with this ;)

**Comment by codeplay-code** [comment]
ok

**Comment by MioVisman** [comment]
https://github.com/forkbb/forkbb/commit/8e3c74367e9f0fbd1adf2332d04b0cf8a53b4b28

**Comment by codeplay-code** [comment]
how to update?

**Comment by MioVisman** [comment]
>how to update?

1. Download the latest revision https://github.com/forkbb/forkbb/releases/tag/0.0071.1
2. Upload new files to your website over old files and replace them.
3. Open the forum page (any) in the browser and enter the password for the database (it is written on the update page) -> an update occurs.

**Comment by codeplay-code** [comment]
olny app files? ok ty

**Comment by MioVisman** [comment]
>olny app files?

Changes can be in all folders, not just app. Depends on the revision.

**Comment by codeplay-code** [comment]
yes yes I understand thanks

**Comment by MioVisman** [comment]
https://github.com/forkbb/forkbb/releases/tag/0.0071.2

**Comment by codeplay-code** [comment]
This change doesn't require a database update right?

I recommend updating the ICU library on your server. According to my feelings (I ran several tests), Transliterator initializes on ICU 71.1 several times faster than on ICU 63.1. what is?

**Comment by MioVisman** [comment]
>This change doesn't require a database update right?

Yes, only one file has been changed.

>what is?

Administration -> Index -> View server statistics -> Show info

![intl](https://github.com/forkbb/forkbb/assets/5917956/29b76e49-acc0-49be-923d-780be0547c9a)

Current ICU version = 74 if I'm reading [the page](https://icu.unicode.org/download) correctly. 

You can ask your hosting support to update this library if it is old. Whether they will update or not is another question.
But you don’t have to ask if there is no noticeable drop in ForkBB execution speed when transliteration is enabled in main.php:
```
    'FRIENDLY_URL' => [
        'lowercase' => true,
        'translit' => 'Russian-Latin/BGN;Any-Latin;Latin-ASCII;',
        'WtoHyphen' => true,
    ],
```
compared to when transliteration is disabled:
```
    'FRIENDLY_URL' => [
        'lowercase' => true,
        'translit' => '',
        'WtoHyphen' => true,
    ],
```

**Comment by codeplay-code** [comment]
my icu 64,2 https://ibb.co/X2LNCWW 
main.php? folder?

**Comment by MioVisman** [comment]
>main.php? folder?

see https://forkbb.ru/topic/63/app-config-main-php
