### ISSUE TITLE
index html templates

### ISSUE THREAD

**Issue by codeplay-code** [forkbb/forkbb#26]
index html templates footer ?

how to add ?[ Generated in 0.046 seconds, 5 queries executed - Memory usage: 1.11M (Peak: 1.23M) ]

**Comment by MioVisman** [comment]
There is no separate footer, there are layouts/main.forkbb.php for almost all pages (but not all).

>how to add ?

https://forkbb.ru/topic/63/%28_backslash_%29app%28_backslash_%29config%28_backslash_%29main.php
see `'DEBUG'`

**Comment by codeplay-code** [comment]
ok :)
