### ISSUE TITLE
new installation

### ISSUE THREAD

**Issue by codeplay-code** [forkbb/forkbb#27]
PHP OTHER_ERROR: Wrong property name: FRIENDLY_URL in .../app/Core/Container.php:[98]

Trace:

.../app/Core/Func.php(53): ForkBB\Core\Container->__get()
.../app/Core/Container.php(126): ForkBB\Core\Func->__construct()
.../app/Models/User/User.php(119): ForkBB\Core\Container->__get()
.../app/Models/Model.php(120): ForkBB\Models\User\User->getlanguage()
.../app/Models/DataModel.php(148): ForkBB\Models\Model->__get()
.../app/Core/Lang.php(125): ForkBB\Models\DataModel->__get()
.../app/Controllers/Install.php(29): ForkBB\Core\Lang->load()
.../app/Core/Container.php(122): ForkBB\Controllers\Install->routing()
.../app/bootstrap.php(80): ForkBB\Core\Container->__get()
.../index.php(14): require(string)
https://forum.codeplaycode.com/

**Comment by MioVisman** [comment]
Try this change.

**Comment by codeplay-code** [comment]
I don't understand why subdivisions don't work  until yesterday everything was OK, from today nothing

**Comment by codeplay-code** [comment]
Solved
