### ISSUE TITLE
error PHP OTHER_ERROR: SQLSTATE[42S02]

### ISSUE THREAD

**Issue by pitamatein** [forkbb/forkbb#29]
_Server is tired_ when using [ Topics with your posts ] link

` 2023-11-21 13:16:34 error PHP OTHER_ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'abolus_forkbb3.forum_topics' doesn't exist in .../app/Core/DB.php:[398] `

**Comment by MioVisman** [comment]
In reality, does the table abolus_forkbb3.forum_topics exist? You didn’t restore the database or did you?

If the table exists, then perhaps this error appears when the SQL server is overloaded.

**Comment by MioVisman** [comment]
I don’t see such an error on your forum for my account (Maybe I don't have enough topics?). It's not in the forum logs either.
If you are moving the database to another server, then look at this question and answers: https://stackoverflow.com/questions/7759170/mysql-table-doesnt-exist-but-it-does-or-it-should

**Comment by pitamatein** [comment]
Sorry, I should have mentioned it is a different domain/install. 
https://www.dissens.us/f/

abolus_forkbb3.forum_topics does exist, and everything seems to work OK except that link. I have been using it as sort of a test site for new revisions before rolling them out on WoodCentral.

**Comment by MioVisman** [comment]
Then show here the full log (with trace) of this error.

**Comment by MioVisman** [comment]
Fixed it. Thanks for the report!

**Comment by MioVisman** [comment]
Fix number 2
