### ISSUE TITLE
HowTO Install?

### ISSUE THREAD

**Issue by halojoy** [forkbb/forkbb#3]
I like your work very much.
FluxBB by MIO-Visman works very well. I use SQLite.

Now I want to try ForkBB.
But when I try I can not install.
How can I install forkBB ?

**Comment by MioVisman** [comment]
Please DO NOT use this revision in production, it is for test only.

1. You need to create a database in MySql (Currently SQLite is not supported). When creating a database, specify the collation = utf8mb4_unicode_ci. 
2. Download the current archive https://github.com/forkbb/forkbb/archive/master.zip (I have made some fixes for the installation now) and unpack it to your host. 
3. Make these changes depending on your server: https://github.com/forkbb/forkbb#install 
4. Go to your host, the installation page should open. If it is not there, then you did the previous step incorrectly.

**Comment by halojoy** [comment]
Thanks.
I will wait until you get the app more mature.
For now it is somewhat complicated.

**Comment by finkiki** [comment]
One little question : 
If I start by using Fluxbb by MioViseman, will it be possible to convert it to forkbb in the future ?

**Comment by MioVisman** [comment]
After I implement Private Messages in ForkBB, I will start writing a FluxBB_by_Visman and FluxBB converter to ForkBB.

**Comment by halojoy** [comment]
Good News!
I managed to install forkBB. It was easy.
I created one mysql database. I run MySQL 8.0.19.
I did the collation you recommended.

Now I have a forkBB running. Just for testing.
It looks very nice.

Thanks for your work and your help.

**Comment by Neogeeo** [comment]
> 
Do you have some link to see how it looks? I can't find any demo of ForkBB but I'm very curious to check the new work of MioVisman

**Comment by MioVisman** [comment]
Test forum: http://forkbb.byethost8.com
Username: **Test**
Passphrase: **test test test test**

P.S. Registration is disabled.

**Comment by Neogeeo** [comment]
> Test forum: http://forkbb.byethost8.com Username: **Test** Passphrase: **test test test test**
> 
> P.S. Registration is disabled.

Thank you! ForkBB looks minimal and fast! I'll keep checking your FBB progress :+1:  

For other hand, do you have any demo for FluxBB_Miovisman_version to check too? I'm fan of your hacks and improvements

**Comment by MioVisman** [comment]
There is no test site for FluxBB_by_Visman.

**Comment by MioVisman** [comment]
> After I implement Private Messages in ForkBB, I will start writing a FluxBB_by_Visman and FluxBB converter to ForkBB.

https://github.com/forkbb/transformer

**Comment by finkiki** [comment]
> > After I implement Private Messages in ForkBB, I will start writing a FluxBB_by_Visman and FluxBB converter to ForkBB.
> 
> https://github.com/forkbb/transformer

Nice, can i start translating forkbb into french or strings could still vary a lot in the near future ?

**Comment by MioVisman** [comment]
I do not foresee strong changes in language files.
Minor edits, new additions will probably still be.

**Comment by MioVisman** [comment]
Related Topics:
https://forkbb.ru/topic/28/ustanovka-installation
https://forkbb.ru/topic/36/new-install-not-seeing-stylesheet
