### ISSUE TITLE
Style link issue

### ISSUE THREAD

**Issue by halojoy** [forkbb/forkbb#6]
CSS link is displayed like: public/style/ForkBB/style.v.1638872941.css
Should be public/style/ForkBB/style.css
It is added one Unix timestamp.
So, to begin with there is no style for me.

**Comment by MioVisman** [comment]
public/style/ForkBB/style.v.1638872941.css - Correct link. Changed when the stylesheet is updated. 
Htaccess Rewrite rules (if your server is Apache) or Nginx config rules (if your server is Nginx) should work. 

https://github.com/forkbb/forkbb#install - rename files for Apache or configure Nginx config.
