### ISSUE TITLE
PostgreSQL: case sensitive, LIKE and indexes, collate

### ISSUE THREAD

**Issue by MioVisman** [forkbb/forkbb#8]
https://github.com/forkbb/forkbb/pull/7

I have several problems with PostgreSQL:
1. case sensitive - Is there a normal (?) solution only in PostgreSQL 12? https://postgrespro.ru/docs/postgresql/12/sql-createcollation
2. collate - Only "C"? If I change to something other than "C" LIKE stops using the index. 
3. LIKE and indexes - B-tree indexes fail when collate changes even for LIKE 'abc%'? For PostgreSQL, I have to create non-MySQL indexes :(

![stat1](https://user-images.githubusercontent.com/5917956/145680299-d5ebc847-dcaf-4835-970b-870d2b49feef.png)
![uslist](https://user-images.githubusercontent.com/5917956/145680366-92fda01e-e5a9-4472-b521-1c0e2ececa45.png)

**Comment by MioVisman** [comment]
4. ILIKE and collate С work only with Latin?

**Comment by halojoy** [comment]
You can make CI when you create tables.
Put CITEXT on the row inquestionn.

$sql = "CREATE EXTENSION IF NOT EXISTS citext";

$pg->exec($sql);

`$sql = "CREATE TABLE IF NOT EXISTS books (

id SERIAL PRIMARY KEY,

author CITEXT,

title CITEXT,

year INTEGER)";

$pg->exec($sql);`

**Comment by MioVisman** [comment]
CITEXT does not support UTF-8, as it is not a real case insensitive, but an analogue of `WHERE LOWER(field) LIKE LOWER(value)`

**Comment by MioVisman** [comment]
I figured out why the LOWER() and UPPER() functions didn't work with UTF-8. Because of COLLATE "C". I will test CREATE COLLATION with PROVIDER = icu.

**Comment by MioVisman** [comment]
Did so https://github.com/forkbb/forkbb/commit/65941831e5ae36af3deaeafa5e87f4be033420b3 https://github.com/forkbb/forkbb/commit/ee0f448a89ff7b7d39e1b708194475ed52558158
ILIKE began to understand UTF-8.

Sort order username:
![users](https://user-images.githubusercontent.com/5917956/152744548-01e2bc67-12ae-4b46-89f1-d037369b2a47.png)
